import pandas as pd,numpy as np,matplotlib.pyplot as plt
from pathlib import Path
R=Path(__file__).resolve().parents[2];O=R/'phase1/results/phase1c_candidate_generation';e=pd.read_parquet(R/'outputs/tables/dataset_a_events_with_gt.parquet').sort_values(['session_id','timestamp_ms','raw_line_number']).reset_index(drop=True)
e['p']=e.groupby('session_id').execution_id.shift();e['pt']=e.groupby('session_id').timestamp_ms.shift();e['gap']=((e.timestamp_ms-e.pt)/1000).clip(0,120);e['true_boundary']=e.execution_id.notna()&e.p.notna()&e.execution_id.ne(e.p);e['app_change']=e.active_app.ne(e.groupby('session_id').active_app.shift());e['window_change']=e.window_title.ne(e.groupby('session_id').window_title.shift());e['browser_action']=e.event_type.isin(['browser_navigation','browser_form_input']);e['clipboard']=e.event_type.eq('clipboard_change');e['density_shift']=e.gap>e.groupby('session_id').gap.transform(lambda x:x.quantile(.9));e['candidate']=e.p.notna()&( (e.gap>1)|e.app_change|e.window_change|e.browser_action|e.clipboard|e.density_shift )
def ctx(i,k=20):
 x=e.iloc[max(0,i-k):min(len(e),i+k)];return {'context_events':len(x),'pre_sequence':' > '.join(e.iloc[max(0,i-k):i].event_type.tail(10)),'post_sequence':' > '.join(e.iloc[i:min(len(e),i+k)].event_type.head(10)),'pre_apps':' > '.join(e.iloc[max(0,i-k):i].active_app.dropna().drop_duplicates()),'post_apps':' > '.join(e.iloc[i:min(len(e),i+k)].active_app.dropna().drop_duplicates()),'pre_text':str(e.iloc[max(0,i-k):i].extracted_text.dropna().iloc[-1])[:200] if e.iloc[max(0,i-k):i].extracted_text.notna().any() else None,'post_text':str(e.iloc[i:min(len(e),i+k)].extracted_text.dropna().iloc[0])[:200] if e.iloc[i:min(len(e),i+k)].extracted_text.notna().any() else None}
C=e[e.candidate].copy(); rows=[]
for i,r in C.head(2000).iterrows(): rows.append({**r[['session_id','timestamp_iso','gap','true_boundary','app_change','window_change','browser_action','clipboard','density_shift']].to_dict(),**ctx(i)})
X=pd.DataFrame(rows);X['signal_count']=X[['app_change','window_change','browser_action','clipboard','density_shift']].sum(axis=1)+(X.gap>1);X['bucket']=np.where(X.true_boundary,'likely_boundary_observed',np.where(X.signal_count>=3,'ambiguous_multi_signal','likely_nonboundary'))
X.to_csv(O/'context_features.csv',index=False);X.head(1000).to_csv(O/'candidate_examples.csv',index=False)
st=pd.DataFrame([{'gt_boundaries':int(e.true_boundary.sum()),'candidates':len(C),'candidate_recall':float(C.true_boundary.sum()/e.true_boundary.sum()),'candidates_per_session':len(C)/e.session_id.nunique(),'candidate_density':len(C)/(len(e)-e.session_id.nunique()),'observed_true_candidates':int(C.true_boundary.sum()),'ambiguous_multi_signal':int((X.bucket=='ambiguous_multi_signal').sum())}]);st.to_csv(O/'candidate_statistics.csv',index=False)
fig,ax=plt.subplots();C.groupby('session_id').size().hist(ax=ax,bins=20);ax.set_title('Candidate count per session');ax.set_xlabel('candidates');fig.tight_layout();fig.savefig(O/'plots/candidate_volume.png',dpi=160);plt.close(fig);print(st.to_dict('records')[0])

